### import necessary libraries

In [47]:
import pandas as pd
import matplotlib. pyplot as plt
import seaborn as sns

import warnings
warnings. filterwarnings('ignore')

### import Datas

In [48]:
students_data = pd. read_csv('Student_Performance.csv')
students_data

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [49]:
students_data.shape

(10000, 6)

In [50]:
students_data.isna().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [51]:
students_data.dtypes

Hours Studied                         int64
Previous Scores                       int64
Extracurricular Activities           object
Sleep Hours                           int64
Sample Question Papers Practiced      int64
Performance Index                   float64
dtype: object

In [52]:
students_data['Extracurricular Activities'] = students_data['Extracurricular Activities'].replace({'Yes':1,'No':0})
students_data

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,1,4,2,23.0
9996,7,64,1,8,5,58.0
9997,6,83,1,8,5,74.0
9998,9,97,1,7,0,95.0
9999,7,74,0,8,1,64.0

In [53]:
students_data.dtypes

Hours Studied                         int64
Previous Scores                       int64
Extracurricular Activities            int64
Sleep Hours                           int64
Sample Question Papers Practiced      int64
Performance Index                   float64
dtype: object

### Data Assumption

In [62]:
students_data.corr()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
Hours Studied,1.000000,-0.012390,0.003873,0.001245,0.017463,0.373730
Previous Scores,-0.012390,1.000000,0.008369,0.005944,0.007888,0.915189
Extracurricular Activities,0.003873,0.008369,1.000000,-0.023284,0.013103,0.024525
Sleep Hours,0.001245,0.005944,-0.023284,1.000000,0.003990,0.048106
Sample Question Papers Practiced,0.017463,0.007888,0.013103,0.003990,1.000000,0.043268
Performance Index,0.373730,0.915189,0.024525,0.048106,0.043268,1.000000

### data preparation

In [21]:
X = students_data.drop(labels = 'Performance Index',axis = 1)
X

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
0,7,99,1,9,1
1,4,82,0,4,2
2,8,51,1,7,2
3,5,52,1,5,2
4,7,75,0,8,5
...,...,...,...,...,...
9995,1,49,1,4,2
9996,7,64,1,8,5
9997,6,83,1,8,5
9998,9,97,1,7,0
9999,7,74,0,8,1

In [22]:
y = students_data['Performance Index']
y

0       91.0
1       65.0
2       45.0
3       36.0
4       66.0
        ...
9995    23.0
9996    58.0
9997    74.0
9998    95.0
9999    64.0
Name: Performance Index, Length: 10000, dtype: float64

In [23]:
from sklearn. model_selection import train_test_split

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42,shuffle=True)

In [25]:
X_train.shape, y_train.shape

((8000, 5), (8000,))

In [26]:
X_test.shape, y_test.shape

((2000, 5), (2000,))

### Model Building & Calling

In [27]:
from sklearn.linear_model import LinearRegression

In [28]:
Linear_model = LinearRegression()

### Model Traning

In [29]:
Linear_model.fit(X_train,y_train)

LinearRegression()

In [30]:
Linear_model.fit(X_test,y_test)

LinearRegression()

### Model Testing

In [35]:
y_pred_train = Linear_model.predict(X_train)
print(y_pred_train)

[34.25332212 25.48435261 57.85578617 ... 44.85324756 20.76334281
 22.32167261]

In [38]:
y_pred_testing = Linear_model.predict(X_test)
print(y_pred_testing)

[54.62623802 22.3606004  47.75614544 ... 16.48934763 63.36146087
 45.81025017]

### Model Evaluation Metrics

In [39]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error, r2_score

In [46]:
mean_absolute_error(y_train,y_pred_train),mean_squared_error(y_train,y_pred_train),root_mean_squared_error(y_train,y_pred_train),r2_score(y_train,y_pred_train)

(1.6237552368861787, 4.192042354750256, 2.047447766061507, 0.9886293742111494)

In [64]:
mean_absolute_error(y_test,y_pred_testing),mean_squared_error(y_test,y_pred_testing),root_mean_squared_error(y_test,y_pred_testing),r2_score(y_test,y_pred_testing)

(1.6052886564523623, 4.059370841832032, 2.0147880389341286, 0.989046049971872)

### Very Important Metrics adjacent r2 Score Checking

In [69]:
import statsmodels.formula.api as sms

In [66]:
students_data.head(5)

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0

### column names space then added Q

In [81]:
linear_stats_model = sms.ols(
    formula='Q("Performance Index") ~ Q("Hours Studied") + Q("Previous Scores") + Q("Extracurricular Activities") + Q("Sleep Hours") + Q("Sample Question Papers Practiced") ',
    data=students_data
).fit()

In [82]:
linear_stats_model. rsquared_adj

np.float64(0.9887467051679587)

In [86]:
y_states_test = linear_stats_model.predict(X_test)
y_states_test

6252    54.693364
4684    22.563903
1731    47.873428
4742    31.242927
4521    42.957350
          ...
6412    46.866094
8285    62.699086
7853    16.732164
1095    63.346325
6929    45.915060
Length: 2000, dtype: float64

In [87]:
r2_score(y_test,y_states_test)

0.9890065971120935

### This Data Model Good

### Model Deployment

In [88]:
from pickle import dump

In [93]:
dump(Linear_model,open('linear_model.pkl','wb'))

### The End